iansworld/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('', views.HomePage.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('titanic/',include('titanic.urls', namespace='titanic')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

titanic/urls.py
from django.urls import path,include,re_path
from titanic import views
from rest_framework import routers

router = routers.DefaultRouter()


app_name='titanic'
urlpatterns = [
    path('',views.Titanic_Home,name='titanic_home'),
    #path('api/', include(router.urls)),
    #path('home/', views.Titanic_Home,name='titanic_home'),
    path('result/', views.result, name='result'),
]

skills/models.py
from django.db import models

# Create your models here.

titanic/models.py
from django.db import models

# # Create your models here.
# class titanic_guess(models.Model):

#     class Gender(models.IntegerChoices):
#         FEMALE = 0
#         MALE = 1
#     class Pclass(models.IntegerChoices):
#         FIRST = 1
#         SECOND = 2
#         THIRD = 3

#     sex=models.IntegerField(choices=Gender.choices)
#     pclass=models.IntegerField(choices=Pclass.choices)
#     age=models.IntegerField(default=0)
#     relatives=models.IntegerField(default=0)
#     fare=models.FloatField(default=0)
#     result=models.IntegerField(default=0)

#     def __str__(self):
#         return super().__str__()

titanic/forms.py
from django import forms


class TitanicForm(forms.Form):

    sex=forms.ChoiceField(choices=[(0, "Female"), (1, "Male") ])
    pclass=forms.ChoiceField(choices=[(1, "First"), (2, "Second"), (3, "Third") ], label="Passenger Class")
    age=forms.IntegerField()
    relatives=forms.IntegerField()
    fare=forms.FloatField()
	

iansworld/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomePage(TemplateView):
    template_name = 'index.html'

skills/views.py
from django.shortcuts import render

# Create your views here.

titanic/views.py
from django.views.generic import TemplateView, View
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.decorators import api_view
from django.core import serializers
from django.contrib import messages
from rest_framework.response import Response
from rest_framework import status
from django.http import JsonResponse
from rest_framework.parsers import JSONParser
from . forms import TitanicForm
from . import functions
import os
import pickle
import json
import numpy as np
from sklearn import preprocessing
import pandas as pd
from sklearn.preprocessing import StandardScaler
from joblib import load


# Create your views here.
def Titanic_Home(request):
	form=TitanicForm()
	return render(request,'titanic/titanic_home.html', {'form': form})


def result(request):
		if request.method =='POST':
			form=TitanicForm(request.POST)
			if form.is_valid():
				sex=request.POST.get('sex')
				pclass=request.POST.get('pclass')
				age=request.POST.get('age')
				relatives=request.POST.get('relatives')
				fare=request.POST.get('fare')

				context = {
					'sex': sex,
					'pclass': pclass,
					'age': age,
					'relatives': relatives,
					'fare': fare,
				}
				#create Dataframe
				df=pd.DataFrame(context, index=[0])
				#send df to model
				titanic_mdl_location = os.path.join('titanic', 'titanic_model.pkl')
				titanic_sc_location = os.path.join('titanic', 'scalars.pkl')
				mdl=load(titanic_mdl_location)
				sc=load(titanic_sc_location)
				# mdl=load("/Users/user/projects/iansworld/titanic/titanic_model.pkl")
				# sc=load("/Users/user/projects/iansworld/titanic/scalars.pkl")
				df=sc.transform(df)
				y_pred=mdl.predict_classes(df)
				y_pred=pd.DataFrame(y_pred, columns=['Survived'])
				y_pred=y_pred.replace({1:'Lived', 0:'Perished'})
				form=TitanicForm()

			return render(request, 'titanic/result.html', {'pred': y_pred.iloc[0]['Survived']})
		
		else:
			form=TitanicForm()

		return render(request, 'titanic/titanic_home.html', {'form': form})

templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>Ian's World</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'index'%}" class="nav-link">Home</a>
      </li>
      {% comment %} 
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li> 
      {% endcomment %}
    </ul>
  </nav>
  <!-- /.navbar --> 


  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
   
    <a href="{% url 'index' %}" class="brand-link">
      <img class="img-thumbnail" src="{% static 'images/Ians_World_Logo.png' %}" alt="Logo">
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      {% comment %} <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'admin-lte/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div> {% endcomment %}

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Machine Learning
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'titanic:titanic_home'%}" class="nav-link">
                  <i class="fa fa-ship nav-icon"></i>
                  <p>Titanic</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-star nav-icon"></i>
                  <p>Job Skills</p>
                </a>
              </li>
            </ul>
          </li>
          {% comment %} 
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Simple Link
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li> {% endcomment %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block content%}
    {% endblock %}
  </div>
  <!-- /.content-wrapper -->

  {% comment %} 
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar --> {% endcomment %}

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2020 <a href="">Ian's World</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script>
  $(document).ready(function(){
    {% block jquery %}{% endblock %}
  })
</script>

<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin-lte/dist/js/adminlte.min.js'%}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<style>
.hero-image {
  background-image: url("../../static/images/HKsunrise.jpg");
  background-color: #cccccc;
  height: 500px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

.hero-text {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
}
</style>

<div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size:50px">Welcome to Ian's Testing Grounds</h1>
  </div>
</div>
<div class="row">
  <div class="container" style="text-align:center">
    <h2>I like to learn new skills every morning before I start work.</h2>
    <h3>I will post the output of some of my projects on this site for everyone to see!</h3>
  </div>
</div>


{% endblock  %}

templates/titanic/result.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<style>
.card-text{
  color: blue;
  font-size: 48pt;
  text-align: center;

}

</style>

<section class="col-lg-12">
  <div class="row justify-content-center">
    <div class="col-lg-9">
      <div class="card">
        <div class="card-body">
          <p class="card-text">
            You {{pred}}
          </p>
        </div>
      </div>



{% endblock  %}

templates/titanic/titanic_home.html
<!DOCTYPE html>
{% extends 'base.html' %}
<style>

</style>

{% block content %}
{% load static %}
{% load crispy_forms_tags %}
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <section class="col-lg-12">
            <div class="row">
              <div class="col-lg-6">
                <div class="card">
                  <div class="card-body">
                    <p class="card-text">
                      The Titanic survival prediction is the starting point for testing out machine learning knowledge.
                    </p>
                  </div>
                </div>
                <div class="card card-primary card-outline">
                  <div class="card-header">
                    <h5 class="card-title">Test Data Results</h5>
                  </div>
                  <div class="card-body">
                      <p class="card-text">
                        This model is a Keras sequential model using an Adam optmizer using 80% of the data as test. Here we 
                        are able to see the relationships between various features in the data.
                      </p>
                    <ul class = "fa-ul">
                      <li><span class="fa-li"><i class="fa fa-bolt" style=" color:#32CD32 "></i></span>5 primary features are ultimately used for testing</li>
                      <li><span class="fa-li"><i class="fa fa-bolt" style=" color:#32CD32 "></i></span>Over 800 passenger records are tested on</li>
                      <li><span class="fa-li"><i class="fa fa-bolt" style=" color:#32CD32 "></i></span>The network uses 3 layers for prediction</li>
                    </ul>
                    <p class="card-text">
                    The final result is 81% accurate! I have created a form so you can play around with the predictions yourself!
                    </p>
                  </div>
                </div><!-- /.card -->
              </div>
              <div class="col-lg-6">
                    <img class="mx-auto d-block" style="height:300px" src="{% static 'titanic/titanic.png' %}">
              </div>
            </div>  
          </section>
        </div>

        <div class="row">
          <section class="col-lg-12">
            <div class="card card-primary card-outline">
              <img src="{% static 'titanic/titanic_model.png' %}" class="card-img-top" alt="">
              <div class="card-body">
                <h5 class="card-text">Feature Relations</h5>
              </div>
            </div>
          </section>
        </div>
        <!-- /.row -->
        <div class="row justify-content-center">
          <div class="col-lg-4">
            <form action='result/' method='post'>
              {% csrf_token %}
              {{form|crispy }}
              <input type='submit' value="Submit">
            </form>



          </div>
        </div>
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->

{% endblock  %}